config/routes.rb
Rails.application.routes.draw do
  root :to =>  'pages#home'

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  get 'carts/show'

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  

  resources :products
  resources :orders

  resources :users, :only => [:index, :new, :create]

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'login' => 'session#destroy'

  get 'users/:id' => 'users#show', :as => :user

  get 'shops/index' => 'shops#index'
  get 'shops/new' => 'shops#new'
  get 'shops/:id' => 'shops#show', :as => :shop
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items
    belongs_to :user, :optional => true
    
    def sub_total
        sum = 0
        self.line_items.each do |line_item|
          sum+= line_item.total_price
        end
        return sum
      end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product, :optional => true
  belongs_to :cart, :optional => true
  belongs_to :order, :optional => true

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    belongs_to :user, :optional => true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :line_items, dependent: :destroy
    belongs_to :shop, :optional => false
    has_many :reviews

    def self.search(search)
        if search
            where(["name ILIKE ?","%#{search}%"])
        else
            all
        end
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user, :optional => false
    belongs_to :product, :optional => false
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_and_belongs_to_many :users
    has_many :products

    def self.search(search)
        if search
            where(["name ILIKE ?","%#{search}%"])
        else
            all
        end
    end
end

app/models/shops_user.rb
class ShopsUser < ApplicationRecord
  belongs_to :shop
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, :presence => true, :uniqueness => true
    has_secure_password
    has_many :orders
    has_one :cart
    has_and_belongs_to_many :shops
    has_many :reviews
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def new
  end

  def index
    @shops = Shop.search(params[:search])
  end

  def show
    @shop = Shop.find params[:id]
  end

  private
  def user_params
    params.require(:shop).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end
  def show
    @user = User.find params[:id]
  end
  def create
    @user = User.create user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
  def update
    user = User.find params[:id]
    user.update user_params
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_order
        if Order.find_by_id(session[:order_id]).nil?
            Order.new
        else
            Order.find_by_id(session[:order_id])
        end
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<h2>Cart show</h2>
  <% @cart.line_items.each do |line_item| %>
  <div class="product_in_cart">
    <b><%= line_item.product.name %> <span style="float: right; font-size: 30px;"><%= number_to_currency(line_item.product.price) %></span></b>
      <div class="quantity">
        <span>Quantity:</span>
        <span><%= button_to "+", line_item_add_path(:id => line_item), method: :post %></span>
        <span><%= line_item.quantity %></span>
        <span><%= button_to "-", line_item_reduce_path(:id => line_item), method: :post%></span>
      </div>
      <%= link_to "Remove item", line_item_path(line_item), method: :delete %>
  </div>
  <% end %>
<h3>Sub total: <%= number_to_currency(@cart.sub_total) %></h3>
<%= link_to "Proceed to checkout", new_order_path %><br>
<%= link_to "Empty cart", cart_path(@current_cart),method: :delete, data: {confirm: "Are you sure?"}%>

app/views/shops/index.html.erb
<h2>Featured Shops</h2>
<%= form_tag shops_index_path, :method => 'get' do %>
<p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search"%>
</p>
<% end %>
<% @shops.each do |shop| %>
    <a href = <%= shop.id %>, class = 'shop'>
        <div class = 'shop'>
            <h3><%= shop.name %></h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>    
            Users:
            <% shop.users.each do |user| %>
            <li><%= user.username %></li>
            <% end %>
        </div>
    </a>
<% end %>

app/views/shops/new.html.erb
<h1>New Shop</h1>
<p>Coming soon.</p>

app/views/shops/show.html.erb
<h2><%= @shop.name %></h2>
<small>Created: <%=@shop.created_at.day%>/<%=@shop.created_at.month%>/<%=@shop.created_at.year%></small>
<p>Description Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<b>Users</b>
<% @shop.users.each do |user| %>
<li><%= link_to user.username, ('/users/'+(user.id).to_s) %></li>
<% end %>
<br>
<% @shop.products.each do |product| %>
    <a href = <%= product_path(product.id) %> >
        <div class = 'product'>
            <h3><%= product.name %> | <%= number_to_currency(product.price) %></h3>
            <h4><%= product.shop.name %></h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>    
            <% if product.image? %>
            <img src ='<%= product.image %>' height = '150px'>
            <% else %>
            <img src ='https://via.placeholder.com/150'>
            <% end %>
        </div>
    </a>
<% end %>

app/views/users/index.html.erb
<h2>Users</h2>
A total of <%= User.count %> users.
<table>
    <tr>
        <th>User ID</th>
        <th>Username</th>
        <th>Email</th>
        <th>Admin</th>
    </tr>
    <% @users.each do |user| %>
        <tr>
            <td><%= user.id %></td>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td><% if user.admin %>True<%else%>False<% end %></td>
        </tr>
    <% end %>
</table>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ol>
<% end %>

<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :email %>
    <%= f.email_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Sign Up!" %>
<% end %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
<small>Created: <%=@user.created_at.day%>/<%=@user.created_at.month%>/<%=@user.created_at.year%></small>
<p>Description Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<b>Shops</b>
<% @user.shops.each do |shop| %>
<li><%= link_to shop.name, ('/shops/'+(shop.id).to_s) %></li>
<% end %>