config/routes.rb
Rails.application.routes.draw do
  root :to =>  'pages#home'

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  get 'carts/show'

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  

  resources :products
  resources :orders

  resources :users, :only => [:index, :new, :create]

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'login' => 'session#destroy'

  get 'users/:id' => 'users#show', :as => :user

  get 'shops/index' => 'shops#index'
  get 'shops/new' => 'shops#new'
  get 'shops/:id' => 'shops#show', :as => :shop
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items
    belongs_to :user, :optional => true
    
    def sub_total
        sum = 0
        self.line_items.each do |line_item|
          sum+= line_item.total_price
        end
        return sum
      end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product, :optional => true
  belongs_to :cart, :optional => true
  belongs_to :order, :optional => true

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    belongs_to :user, :optional => true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :line_items, dependent: :destroy
    belongs_to :shop, :optional => false
    has_many :reviews

    def self.search(search)
        if search
            where(["name ILIKE ?","%#{search}%"])
        else
            all
        end
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user, :optional => false
    belongs_to :product, :optional => false
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_and_belongs_to_many :users
    has_many :products

    def self.search(search)
        if search
            where(["name ILIKE ?","%#{search}%"])
        else
            all
        end
    end
end

app/models/shops_user.rb
class ShopsUser < ApplicationRecord
  belongs_to :shop
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, :presence => true, :uniqueness => true
    has_secure_password
    has_many :orders
    has_one :cart
    has_and_belongs_to_many :shops
    has_many :reviews
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find params[:id]
  end

  def index
    @products = Product.search(params[:search])
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.create(product_params)
    redirect_to products_path
  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
  
  private
  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def new
  end

  def index
    @shops = Shop.search(params[:search])
  end

  def show
    @shop = Shop.find params[:id]
  end

  private
  def user_params
    params.require(:shop).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_order
        if Order.find_by_id(session[:order_id]).nil?
            Order.new
        else
            Order.find_by_id(session[:order_id])
        end
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :required => true,%>
  <%= f.label :image %>
  <%= f.url_field :image, :required => true,%>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.label :category_id %>
  <%= f.select :category_id, Category.pluck(:title, :id), :include_blank => true %>
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render :partial => "form" %>

app/views/products/index.html.erb
<h2>Featured Products</h2>
<%= form_tag products_path, :method => 'get' do %>
<p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search"%>
</p>
<% end %>
<% @products.each do |product| %>
    <a href = <%= product_path(product.id) %> >
    
        <div class = 'product'>
            <h3><%= product.name %> | <%= number_to_currency(product.price) %></h3>
            <h4><%= product.shop.name %></h4>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>    
            <% if product.image? %>
                <img src ='<%= product.image %>' height = '150px'>
            <% else %>
                <img src ='https://via.placeholder.com/150'>
            <% end %>
        </div>
    </a>
<% end %>

app/views/products/new.html.erb
<h2>New Product</h2>
<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, :required => true %><br>
    <%= f.label :price %>
    <%= f.number_field :price, step: 0.01, :required => true %><br>
  </p>
  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<h2><%= @product.name %> - <%= number_to_currency(@product.price) %></h2>
<%= button_to "Add to cart", line_items_path(:product_id => @product.id), :method => "post" %>
<img src = '<%= @product.image %>' height = '500px' class='product_image' >
<p>Description Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<small>Created: <%=@product.created_at.day%>/<%=@product.created_at.month%>/<%=@product.created_at.year%></small><br>Product of <b><%= link_to @product.shop.name, ('/shops/'+(@product.shop.id).to_s) %></b>
<h3>Reviews</h3>
<% @product.reviews.each do |review|%>
<div class="review">
    <div>
        <img src = 'https://t4.ftcdn.net/jpg/00/64/67/63/360_F_64676383_LdbmhiNM6Ypzb3FM4PPuFP9rHe7ri8Ju.jpg' height = '75px' > 
    </div>
    <div>
        <h4><a href = <%= user_path(review.user.id) %>><%= review.user.username %></a></h4>
        <p><%= review.content %></p>
        <small>Posted: XX/XX/XXXX</small>
    </div>
</div>
<% end %>