config/routes.rb
Rails.application.routes.draw do
  root :to =>  'pages#home'

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  get 'carts/show'

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"
  

  resources :products
  resources :orders

  resources :users, :only => [:index, :new, :create]

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'login' => 'session#destroy'

  get 'users/:id' => 'users#show', :as => :user

  get 'shops/index' => 'shops#index'
  get 'shops/new' => 'shops#new'
  get 'shops/:id' => 'shops#show', :as => :shop
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
    has_many :line_items, dependent: :destroy
    has_many :products, through: :line_items
    belongs_to :user, :optional => true
    
    def sub_total
        sum = 0
        self.line_items.each do |line_item|
          sum+= line_item.total_price
        end
        return sum
      end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product, :optional => true
  belongs_to :cart, :optional => true
  belongs_to :order, :optional => true

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    belongs_to :user, :optional => true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :line_items, dependent: :destroy
    belongs_to :shop, :optional => false
    has_many :reviews

    def self.search(search)
        if search
            where(["name ILIKE ?","%#{search}%"])
        else
            all
        end
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user, :optional => false
    belongs_to :product, :optional => false
end

app/models/shop.rb
class Shop < ApplicationRecord
    has_and_belongs_to_many :users
    has_many :products

    def self.search(search)
        if search
            where(["name ILIKE ?","%#{search}%"])
        else
            all
        end
    end
end

app/models/shops_user.rb
class ShopsUser < ApplicationRecord
  belongs_to :shop
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, :presence => true, :uniqueness => true
    has_secure_password
    has_many :orders
    has_one :cart
    has_and_belongs_to_many :shops
    has_many :reviews
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = @current_cart
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_order
        if Order.find_by_id(session[:order_id]).nil?
            Order.new
        else
            Order.find_by_id(session[:order_id])
        end
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1><%= link_to "MyShop", root_path%></h1>
    <nav>
    <% if @current_user.present? %>
      <%= link_to "Log Out (#{@current_user.username})", login_path, :method => 'delete' %> | 
      <% if @current_user.admin? %>
        <%= link_to "Users", users_path%> | 
      <% end  %>
    <% else %>
      <%= link_to 'Sign Up', new_user_path %> | 
      <%= link_to 'Sign In', login_path%> | 
    <% end %>
    <%= link_to "Shops", shops_index_path %> | 
    <%= link_to "Products", products_path%> | 
    <%= link_to 'Cart', cart_path(@current_cart) %> 
  </nav>
    <div class = 'container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% if @current_user.present? %>
<h2>Welcome <%= @current_user.username %></h2>
<% else %>
<h2>Welcome<h2>
<% end %>